- hosts: all
  tasks:
  - command: "kubeadm token create --print-join-command"
    register: join
    when: inventory_hostname in groups['k8s_master']
   

  - debug:
          msg: "{{ join.stdout }}"
    register: join_cmd
    when: inventory_hostname in groups['k8s_master']


  - debug:
          msg: "{{ join_cmd }}"
    when: inventory_hostname in groups['k8s_master']

  - shell: "{{ join_cmd }}"
    when: inventory_hostname in groups['k8s_worker']
