- hosts: all
  roles:

          - role: k8s_master
            when: inventory_hostname in groups['tag_Name_kubeMaster']
          - role: k8s_worker
            when: inventory_hostname in groups['tag_Name_kubeWorker']
          - role: join_cluster
