---
# tasks file for k8s_master


- name: "Installing Docker"
  include_tasks: docker.yml

- name: "Configure kubernetes Repo and Install Required Softwares for Cluster"
  include_tasks: kubernetes.yml

- name: "Pulling Required Docker Images"
  shell: "kubeadm config images pull"

- name: "Configuring The Network"
  template:
          dest: "/etc/sysctl.d/k8s.conf"
          src: k8s.conf
  register: network_conf

- name: "Starting sysctl service"
  shell: "sysctl --system"
  when: network_conf['changed'] == True

- name: "Check If kubeadm Has Already Run or Not"
  stat:
          path: "/etc/kubernetes/pki/ca.key"
  register: "kubeadm_check"
  ignore_errors: yes

- name: "Initializing kubeadm and ignoring RAM and CPU errors"
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  when: not kubeadm_check.stat.exists
  run_once: yes

- name: "Create Kubernetes config directory"
  file:
           path: "$HOME/.kube/"
           state: directory

- name: "Copy admin.conf to Home directory and changing the Ownership"
  copy:
          dest: "$HOME/.kube/config"
          src: "/etc/kubernetes/admin.conf"
          owner: "{{ ansible_user | default(ansible_user_id) }}"
          group: "{{ ansible_user | default(ansible_user_id) }}"
          mode: 0755
          remote_src: true

- name: "Setting up Overlay Network Using Flannel"
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
