---
# tasks file for k8s_worker


- name: "Installing Docker"
  include_tasks: docker.yml

- name: "Configure Kubernetes Repo and Install Required Softwares For Cluster"
  include_tasks: kubernetes.yml

- name: "Configuring The Network"
  template:
          dest: "/etc/sysctl.d/k8s.conf"
          src: k8s.conf
  register: network_conf

- name: "Starting sysctl service"
  shell: "sysctl --system"
  when: network_conf['changed'] == True
