- name: "Printing join command"
  command: "kubeadm token create --print-join-command"
  register: join_token
  when: inventory_hostname in groups['master']

- name: "Ensure that worker node in join the master or not"
  stat:
        path: "/etc/kubernetes/pki/ca.crt"      
  register: check
  when: inventory_hostname in groups['worker'] 

- name: joining the worker node
  command: "{{ hostvars[item]['join_token']['stdout'] }}"
  with_items: "{{ groups['master'] }}"
  when:
          - inventory_hostname in groups['worker']
          - not check.stat.exists
  run_once: yes           
